version: '3'

x-defaults: &defaults
  image: sparanoid/amsf:latest
  restart: "no"
  volumes:
    - ./_app/_data/:/app/_app/_data
    - ./_app/_pages/:/app/_app/_pages
    - ./_app/_posts/:/app/_app/_posts
    - ./_app/assets/img:/app/_app/assets/img
    - ./_app/assets/_scss:/app/_app/assets/_scss
    - ./_app/_includes/themes/curtana/includes/footer.html:/app/_app/_includes/themes/curtana/includes/footer.html
    - ./_config.yml:/app/_config.yml
  #ports:
    # - "4321:4321"
    # - "35729:35729"

services:
  amsf:
    <<: *defaults
    command: build
